# Generated by Django 3.2.13 on 2023-04-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_timestemp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePost',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=100, verbose_name='Post Title')),
                ('description', models.CharField(max_length=1000, verbose_name='Post Description')),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('good_name', models.CharField(max_length=100, verbose_name='Good Name')),
            ],
        ),
    ]
