# Generated by Django 3.2.13 on 2023-04-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_createpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createpost',
            name='good_name',
        ),
        migrations.AddField(
            model_name='createpost',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
